runtime: nodejs14
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  max_pending_latency: 2000ms


# handlers:
#   - url: /static
#     static_dir: build/static
#   - url: /(.*\.(json|ico|js|css|png|jpg|mp4))$
#     static_files: build/\1
#     upload: build/.*\.(json|ico|js|css|png|jpg|mp4)$
#   - url: .*
#     static_files: build/index.html
#     upload: build/index.html
#     expiration: '0s'